server:
    port: 9002
spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/lanhaifeiyu/tech-config-repo.git
                    #lhfeiyu-robot
                    username: yu_ronghua@126.com
                    password: keep123!
                    search-paths: tech-config-dir
    application:
        name: tech-config-server